### ISSUE TITLE
Duplicate Notebook bug

### ISSUE THREAD

**Issue by benoberlton** [angelolab/toffy#218] opened 2022-08-18 23:43 UTC
When duplicating a notebook, there is a "notebook is not trusted error." However, once closing and reopening the notebook the duplicated notebook will show.

Error: 
![Screenshot 2022-08-18 164245](https://user-images.githubusercontent.com/76409408/185513656-4092067d-20b1-475d-ad81-431d39d03ced.png)

**Comment by ngreenwald** [comment] 2022-08-19 00:17
The random stuff in the terminal doesn't matter, what happens to the actual duplicated notebook?

**Comment by alex-l-kong** [comment] 2022-08-19 00:22
@ngreenwald huh, never seen this error pop up before, I'll take a look into this tomorrow. @benoberlton is this happening on your local machine or on Drago/Creed?

**Comment by benoberlton** [comment] 2022-08-19 00:39
This happened both in the local machine and on the Drago computer
In the actual notebook basically when you click duplicate nothing happens, but when you exit out of the juptyer notebook and restart it, the copied notebook will appear

**Comment by alex-l-kong** [comment] 2022-08-19 22:08
@ngreenwald unable to TeamViewer into Drago today, but I just tested it out on Creed and wasn't able to replicate the error. I plan on meeting with @benoberlton to discuss this issue in more detail.

**Comment by alex-l-kong** [comment] 2022-08-23 17:07
@benoberlton I looked into this a bit more, you might need to explicitly tell Jupyter to trust the notebook (or the copy you made). In the Anaconda terminal, run `jupyter trust {notebook_name}` and see if that does the trick for the future.

I'm hesitant to add explicit documentation for it right now because this issue has only popped up sporadically, but if more in our lab run into it we should put it in the `README.md`.

**Comment by alex-l-kong** [comment] 2022-08-29 19:05
@ngreenwald this should be resolved by the recent PR to move notebooks to a separate `scripts` directory, since users won't need to make notebook copies anymore.

**Comment by ngreenwald** [comment] 2022-08-29 20:30
They will still need to make copies, since different people will have their own version of each notebook.

Next steps for this are figuring out how to reliably reproduce the issue, since Sri said he had it pop up on Drago. Perhaps it's a windows thing?

**Comment by alex-l-kong** [comment] 2022-08-29 20:54
@ngreenwald I think so, haven't had it pop up on my Mac. I know running `jupyter trust` in the command line on the notebooks should work, but if there's a way to do that in Jupyter Lab directly that would be ideal.

**Closed** 2022-12-01 23:40 UTC
Labels: bug
